### ISSUE TITLE
[epic] v0.1 of JS version of frictionless-ckan-mapper

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frictionless-ckan-mapper-js#1]
Port python library below to JS (with a focus on frictionless to ckan for now).

https://github.com/frictionlessdata/frictionless-ckan-mapper

## Acceptance criteria

* [x] I can `yarn add frictionless-ckan-mapper-js`
* [x] It converts my frictionless spec to ckan spec

## Tasks

* [x] Write README file
* [x] Setup the npm project with tests (avajs) and CI using gh actions
* [x] Create set of fixtures for tests
  * [x] resource spec
  * [x] package spec
* [x] Create the functions that converts frictionless => CKAN
   * [x] for package
   * [x] for resource

**Comment by anuveyatsu** [comment]
Hey @kmanaseryan any updates on this issue? Could you please push all your local commits by end of each day so that we can understand the progress?

**Comment by kmanaseryan** [comment]
Hey! Sorry didn't get any updates yesterday as it was during my last one hour that I got to know this. Mainly was playing with the original repo `frictionless-ckan-mapper` to understand the scope.

**Comment by kmanaseryan** [comment]
Created a README file but it's too basic. I will update it along the development of other tasks

**Comment by kmanaseryan** [comment]
Just reused Python tests from original repo to write some basic tests. Going to write test which will read the fixtures and test against that.

**Comment by kmanaseryan** [comment]
Implemented in #3
