### ISSUE TITLE
Implement CKAN => frictionless

### ISSUE THREAD

**Issue by kmanaseryan** [datopian/frictionless-ckan-mapper-js#5]
## Acceptance criteria

* [x] It converts the given ckan spec to frictionless spec
* [x] It passes the tests

## Tasks

* [x] Write tests 
* [x] Implement the algorithm which CKAN => frictionless
   * [x] for package
   * [x] for resource
* [x] Update README accordingly

**Comment by kmanaseryan** [comment]
Implemented in #7
